apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-4wxn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-4wxn@sha256:65b14436e1d80e5c13a1919de0208409fc8ea35e4a777bed82ef1a8970b2a14e
        name: my-python
        resources: {}
status: {}
